### ISSUE TITLE
 Using Location plugin throws an error on filters on OctoberCMS v3.5.14

### ISSUE THREAD

**Issue by salahassi** [rainlab/location-plugin#106]
Please refer to this topic on October Talk.
https://talk.octobercms.com/t/using-rainlabs-location-plugin-throws-an-error-on-filters/2224

Hello,

I have a project that depends on countries in their entries. So, I used Rainlab’s Locations plugin; it worked fine in terms of showing the countries in a dropdown, selecting them, and even showing them in the data table. However, when filtering by country, an error gets thrown as shown:

`"Call to a member function methodExists() on null" on line 237 of /Users/salahassi/dev/sada/october/modules/backend/filterwidgets/Group.php`

The error is here at line 237 ($model is null):
![image](https://github.com/rainlab/location-plugin/assets/1439837/0c6f2096-a238-4207-9b3e-66eea7f02756)

And here is how I define it in the Tailor Blueprint:

```
    country:
        label: Country
        type: dropdown
        options: RainLab\Location\Behaviors\LocationModel::getCountryOptions
        select: name
        placeholder: Select an option
```
I tried to create a custom scope with no luck.

I appreciate any solution or workaround that might help.

Thanks
