### ISSUE TITLE
addressfinder not working in a Relation popup

### ISSUE THREAD

**Issue by AugmentBLU** [rainlab/location-plugin#48]
Hello,

does the addressfinder field work with relation popup forms? I can't seem to get the auto fill inputs to work but not sure if it's the fieldMap. It's difficult to debug or dump data with popups so not sure where I'm going wrong. The actual search function works, just not the input auto fill as I said. 

Thanks!

**Comment by LukeTowers** [comment]
It should work the same, try getting the field map to work correctly within a regular context and then test that same configuration in a relation popup

**Comment by AugmentBLU** [comment]
@LukeTowers I have it working fine in a standard create/update controller page but within a relation popup it doesn't fill in the inputs after finding the address. My YAML is as follows. 

```
simple_address:
            label: Address Finder
            tab: address
            span: full
            type: addressfinder
            countryRestriction: GB
            fieldMap:
                latitude: latitude
                longitude: longitude
                street-number: street_number
                street: street
                city: city
                zip: postcode
                country: country_code
                state: state_code
                vicinity: vicinity

street_number:
            label: Street Number
            tab: address
            span: left
street:
            label: Street
            tab: address
            span: right
city:
            label: City
            tab: address
            span: left
postcode:
            label: Postcode
            tab: address
            span: right
state_code:
            label: State
            tab: address
            span: left
country_code:
            label: Country
            tab: address
            span: right
```

**Comment by AugmentBLU** [comment]
It appears that ```<?= $this->getFieldMapAttributes() ?>``` is not setting the data attributes in the search input so I guess it can't map. Trying to debug anything in popups is near impossible unless I'm doing it wrong. 

Trying to dd out vars just isn't being rendered properly and just shows a ton of ``` +<span class=sf-dump-public title="Public property">valueFrom</span>: "<span class=sf-dump-str title="16 characters">portfolio_assets</span>"```

**Comment by LukeTowers** [comment]
@AugmentBLU have you tried the Debugbar plugin and \Log statements

**Comment by AugmentBLU** [comment]
@LukeTowers I'll take another look at the Debugbar plugin - it caused issues in the past but hopefully they have been ironed out.

Further testing without the Debugbar - the data attributes seem pretty inconsistent which I'm finding odd. On one controller, the address finder is being used in a relation and no data attributes are being generated, on another controller relation it does create data attributes but they are not taking on the unique ID of that relation.

```
data-input-street-number="#Form-field-Landlord-street_number"
```

This should be something like
```
data-input-street-number="#Form-relationLandlordAssetsManageForm-field-PortfolioAsset-street_number"
```

It all seems to point to the `getFieldMapAttributes()` function. Does the code within this support relation fields properly?

```
$widget = $this->controller->formGetWidget();
$fields = $widget->getFields();
```

**Comment by LukeTowers** [comment]
@AugmentBLU that seems to be the problem right there, it's attaching itself to the base controller's form widget, not to the form widget that actually contains the field.

**Comment by AugmentBLU** [comment]
@LukeTowers yeah that's what I thought. Is there a workaround to allow for relations?

**Comment by LukeTowers** [comment]
@AugmentBLU if you do some debugging on the formwidget / formfield object for the addressfinder does it have access to the form widget that it's a part of through one of it's properties?

**Comment by AugmentBLU** [comment]
I haven't managed to get round to checking this as yet but will still be needing this to work with relations. Will take a look when I hit this again.

**Comment by Giseudo** [comment]
I was able to get around this by specifying the target inputs through the `attributes` field property, just like below:

```
fields:
   address:
       label: Address
       type: addressfinder
       countryRestriction: 'br'
       span: right
       attributes:
           data-input-city: '[name="Company[city]"]'
           data-input-state: '[name="Company[state_code]"]'
           data-input-country: '[name="Company[country_code]"]'
           data-input-latitude: '[name="Company[lat]"]'
           data-input-longitude: '[name="Company[lng]"]'
       fieldMap:
           latitude: latitude
           longitude: longitude
           city: city
           country: country_code
           state: state_code
   city:
       label: City
       span: right
   country_code:
       label: Country
       span: right
   state_code:
       label: State
       span: right
   lat:
       label: Latitude
       span: right
   lng:
       label: Longitude
       span: right
```

Where `Company` on the name selector, is the model's name.
