### ISSUE TITLE
addressfinder in plugin settings

### ISSUE THREAD

**Issue by AlexisWalravens** [rainlab/location-plugin#59]
Hi,

So I registered settings for my plugin with `registerSettings()` and tried to put an addressfinder widget inside the form.yaml of my plugin's settings.

But all I get is `Call to undefined method System\Controllers\Settings::formGetWidget()`

Can you help me ?
Thanks.

Here's what inside my form.yaml :  

```
        address:
            label: Address
            type: addressfinder
            tab: Contact details
            fieldMap:
                street: address_street
                city: address_city
                zip: address_zipcode
                latitude: latitude
                longitude: longitude
        address_street:
            type: text
            label: Address Street & Number
            span: full
            tab: Contact details
        address_zipcode:
            label: Zipcode
            type: text
            span: left
            tab: Contact details
        address_city:
            type: text
            label: City
            span: right
            tab: Contact details
        latitude:
            type: text
            label: Latitude
            span: left
            tab: Contact details
        longitude:
            type: text
            label: Longitude
            span: right
            tab: Contact details
```
